import { Component, Input } from '@angular/core';
import { SchedulesByDirection } from '../../interfaces/interfaces';

/**
 * Generated class for the DirectionSchedulesComponent component.
 * See https://angular.io/api/core/Component for more info on Angular
 * Components.
 */
@Component({
    selector: 'direction-schedules',
    templateUrl: 'direction-schedules.html'
})
export class DirectionSchedulesComponent {

    @Input('schedulesByDirection') public schedulesByDirection: SchedulesByDirection[];

    public numberOfSchedulesToShow: number = 3; //Number of schedules shown in the current open accordion
    public selectedAccordionIndex: number = -1; //Index of the direction currently being seen

    constructor() {
        console.log('Hello DirectionSchedulesComponent Component')

        //Mock Data
       /*  this.schedulesByDirection = [
            {
                direction_id: 1,
                direction: {
                    id: 1,
                    lines_id: 1,
                    source: 'CorroiosMadeUp',
                    destination: 'CacilhasMadeUp',
                    time_of_travel: 2000
                },
                schedules: [
                    {
                        id: 1,
                        time_hours: '10:20',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '10:30',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '10:50',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '11:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    }
                ]
            },
            {
                direction_id: 2,
                direction: {
                    id: 2,
                    lines_id: 1,
                    source: 'PragalMadeUp',
                    destination: 'CorroiosMadeUp',
                    time_of_travel: 2000
                },
                schedules: [
                    {
                        id: 1,
                        time_hours: '10:00',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '10:10',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '10:20',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    },
                    {
                        id: 1,
                        time_hours: '10:59',
                        time_minutes: 11,
                        column: 120,
                        directions_id: 1,
                        stations_id: 1,
                        lines_id: 1,
                        schedule_types_id: 1,
                        day_types_id: 1,
                        diffToTimeNow: 12,
                    }
                ]
            }
        ] */
    }

    public toggleDetails(scheduleByDir, index) {
        console.log(scheduleByDir, index);
        if (index === this.selectedAccordionIndex) {
            this.numberOfSchedulesToShow = 0;
            this.selectedAccordionIndex = -1;
        } else {
            this.selectedAccordionIndex = index;
            this.numberOfSchedulesToShow = 3;
        }
        console.log(this.numberOfSchedulesToShow, this.selectedAccordionIndex);
    }

    private show3MoreSchedules(s) {
        console.log(s);
        this.numberOfSchedulesToShow += 3;
    }

}
